name: invq
version: 1.0
main: xiao.da.invq.Invq
description: A plugin to drop a player's inventory items around them.
author: Samisverycute
commands:
  invq:
    description: Drop all items from a player's inventory.
    usage: /invq [player]
permissions:
  invq.use:
    description: Allows the use of /invq command.
    default: op
